#ifndef MY_DESIGNS_H
#define MY_DESIGNS_H

char game_title_original[23][96] = {
    {"RRRRRRRRRRRRRRRRR                                                                              "},
    {"R::::::::::::::::R                                                                             "},
    {"R::::::RRRRRR:::::R                                                                            "},
    {"RR:::::R     R:::::R                                                                           "},
    {"  R::::R     R:::::R   ooooooooooo      ggggggggg   ggggguuuuuu    uuuuuu      eeeeeeeeeeee    "},
    {"  R::::R     R:::::R oo:::::::::::oo   g:::::::::ggg::::gu::::u    u::::u    ee::::::::::::ee  "},
    {"  R::::RRRRRR:::::R o:::::::::::::::o g:::::::::::::::::gu::::u    u::::u   e::::::eeeee:::::ee"},
    {"  R:::::::::::::RR  o:::::ooooo:::::og::::::ggggg::::::ggu::::u    u::::u  e::::::e     e:::::e"},
    {"  R::::RRRRRR:::::R o::::o     o::::og:::::g     g:::::g u::::u    u::::u  e:::::::eeeee::::::e"},
    {"  R::::R     R:::::Ro::::o     o::::og:::::g     g:::::g u::::u    u::::u  e:::::::::::::::::e "},
    {"  R::::R     R:::::Ro::::o     o::::og:::::g     g:::::g u::::u    u::::u  e::::::eeeeeeeeeee  "},
    {"  R::::R     R:::::Ro::::o     o::::og::::::g    g:::::g u:::::uuuu:::::u  e:::::::e           "},
    {"RR:::::R     R:::::Ro:::::ooooo:::::og:::::::ggggg:::::g u:::::::::::::::uue::::::::e          "},
    {"R::::::R     R:::::Ro:::::::::::::::o g::::::::::::::::g  u:::::::::::::::u e::::::::eeeeeeee  "},
    {"R::::::R     R:::::R oo:::::::::::oo   gg::::::::::::::g   uu::::::::uu:::u  ee:::::::::::::e  "},
    {"RRRRRRRR     RRRRRRR   ooooooooooo       gggggggg::::::g     uuuuuuuu  uuuu    eeeeeeeeeeeeee  "},
    {"                                                 g:::::g                                       "},
    {"                                     gggggg      g:::::g                                       "},
    {"                                     g:::::gg   gg:::::g                                       "},
    {"                                      g::::::ggg:::::::g                                       "},
    {"                                       gg:::::::::::::g                                        "},
    {"                                         ggg::::::ggg                                          "},
    {"                                            gggggg                                             "}};

char game_title_design_2[23][100] = {
    {"RRRRRRRRRRRRRRRRR                                                                                  "},
    {"R::::::::::::::::R                                                                                 "},
    {"R::::::RRRRRR:::::R                                                                                "},
    {"RR:::::R     R:::::R                                                                               "},
    {"  R::::R     R:::::R    ooooooooooo       ggggggggg   ggggg uuuuuu    uuuuuu       eeeeeeeeeeee    "},
    {"  R::::R     R:::::R  oo:::::::::::oo    g:::::::::ggg::::g u::::u    u::::u     ee::::::::::::ee  "},
    {"  R::::RRRRRR:::::R  o:::::::::::::::o  g:::::::::::::::::g u::::u    u::::u    e::::::eeeee:::::ee"},
    {"  R:::::::::::::RR   o:::::ooooo:::::o g::::::ggggg::::::gg u::::u    u::::u   e::::::e     e:::::e"},
    {"  R::::RRRRRR:::::R  o::::o     o::::o g:::::g     g:::::g  u::::u    u::::u   e:::::::eeeee::::::e"},
    {"  R::::R     R:::::R o::::o     o::::o g:::::g     g:::::g  u::::u    u::::u   e:::::::::::::::::e "},
    {"  R::::R     R:::::R o::::o     o::::o g:::::g     g:::::g  u::::u    u::::u   e::::::eeeeeeeeeee  "},
    {"  R::::R     R:::::R o::::o     o::::o g::::::g    g:::::g  u:::::uuuu:::::u   e:::::::e           "},
    {"RR:::::R     R:::::R o:::::ooooo:::::o g:::::::ggggg:::::g  u:::::::::::::::uu e::::::::e          "},
    {"R::::::R     R:::::R o:::::::::::::::o  g::::::::::::::::g   u:::::::::::::::u  e::::::::eeeeeeee  "},
    {"R::::::R     R:::::R  oo:::::::::::oo    gg::::::::::::::g    uu::::::::uu:::u   ee:::::::::::::e  "},
    {"RRRRRRRR     RRRRRRR    ooooooooooo        gggggggg::::::g      uuuuuuuu  uuuu     eeeeeeeeeeeeee  "},
    {"                                                   g:::::g                                         "},
    {"                                       gggggg      g:::::g                                         "},
    {"                                       g:::::gg   gg:::::g                                         "},
    {"                                        g::::::ggg:::::::g                                         "},
    {"                                         gg:::::::::::::g                                          "},
    {"                                           ggg::::::ggg                                            "},
    {"                                              gggggg                                               "}};

char game_title_design_3[23][104] = {
    {"RRRRRRRRRRRRRRRRR                                                                                      "},
    {"R::::::::::::::::R                                                                                     "},
    {"R::::::RRRRRR:::::R                                                                                    "},
    {"RR:::::R     R:::::R                                                                                   "},
    {"  R::::R     R:::::R     ooooooooooo        ggggggggg   ggggg  uuuuuu    uuuuuu        eeeeeeeeeeee    "},
    {"  R::::R     R:::::R   oo:::::::::::oo     g:::::::::ggg::::g  u::::u    u::::u      ee::::::::::::ee  "},
    {"  R::::RRRRRR:::::R   o:::::::::::::::o   g:::::::::::::::::g  u::::u    u::::u     e::::::eeeee:::::ee"},
    {"  R:::::::::::::RR    o:::::ooooo:::::o  g::::::ggggg::::::gg  u::::u    u::::u    e::::::e     e:::::e"},
    {"  R::::RRRRRR:::::R   o::::o     o::::o  g:::::g     g:::::g   u::::u    u::::u    e:::::::eeeee::::::e"},
    {"  R::::R     R:::::R  o::::o     o::::o  g:::::g     g:::::g   u::::u    u::::u    e:::::::::::::::::e "},
    {"  R::::R     R:::::R  o::::o     o::::o  g:::::g     g:::::g   u::::u    u::::u    e::::::eeeeeeeeeee  "},
    {"  R::::R     R:::::R  o::::o     o::::o  g::::::g    g:::::g   u:::::uuuu:::::u    e:::::::e           "},
    {"RR:::::R     R:::::R  o:::::ooooo:::::o  g:::::::ggggg:::::g   u:::::::::::::::uu  e::::::::e          "},
    {"R::::::R     R:::::R  o:::::::::::::::o   g::::::::::::::::g    u:::::::::::::::u   e::::::::eeeeeeee  "},
    {"R::::::R     R:::::R   oo:::::::::::oo     gg::::::::::::::g     uu::::::::uu:::u    ee:::::::::::::e  "},
    {"RRRRRRRR     RRRRRRR     ooooooooooo         gggggggg::::::g       uuuuuuuu  uuuu      eeeeeeeeeeeeee  "},
    {"                                                     g:::::g                                           "},
    {"                                         gggggg      g:::::g                                           "},
    {"                                         g:::::gg   gg:::::g                                           "},
    {"                                          g::::::ggg:::::::g                                           "},
    {"                                           gg:::::::::::::g                                            "},
    {"                                             ggg::::::ggg                                              "},
    {"                                                gggggg                                                 "}};

#endif
